language: node_js
node_js:
  - '14'
branches:
  only:
  - master
script: export fev="1.1.$TRAVIS_BUILD_NUMBER" && .travis/script.sh
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: target/index-${fev}.html.gz
  skip_cleanup: true
